#!/bin/bash

#SBATCH --job-name=dora-fw-ddsm
#SBATCH --partition=short
#SBATCH --time=1-
#SBATCH --ntasks=1
#SBATCH --mem=32768
#SBATCH --cpus-per-task=100
#SBATCH --mail-type=ALL,ARRAY_TASKS
#SBATCH --mail-user=dora.he3@monash.edu

### this is temporary to have 100 cores running
#SBATCH --qos=partner



### load the module
module purge
module load python/3.8.5-gcc8

### activate the virtual environment
source ~/td70/py385/bin/activate

python3 ./run-monarch.py

